<?php
// src/df/gcmBundle/Entity/ProductRepository.php
namespace df\gcmBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{
    public function getBenchmark(){
        $result=$this->getEntityManager()
            ->createQuery('SELECT r.topic, r.gameid, COUNT(r.id) AS dings, SUM(r.result) AS dangs, MAX(r.maxresult) AS maxle FROM dfgcmBundle:Result r WHERE 1=1 GROUP BY r.topic, r.gameid')
            ->getResult();        
        return $result;
    }
}
